### PR TITLE
added quick-sort in c

### PR DESCRIPTION
**Pull request by ajyan**
added quick sort algorithm in c, please review

### CODE REVIEW

**Comment by siddeshshewde** [comment]
Nice clean code buddy!
But I think someone is already working on that issue here: https://github.com/siddeshshewde/Algorithms/issues/8
It would be great if you could raise an issue first so that we know you are working on it to avoid any collisions.

**Comment by ajyan** [comment]
ok, if the other person does not complete the issue, can my solution be merged? I didn't realize I needed to open it first, that's for letting me know.

**Comment by siddeshshewde** [comment]
Ofcourse, Ill give him couple of days time. 
Meanwhile would you want to work on some other algo? Let me know

**Comment by siddeshshewde** [comment]
Closing the issue for now. 
Let me know if you want to work on some other algo?

**Pull request closed without merging**
